
element_values_log = {}
attached_files_log = {}

'''
HIGH PRIO:
# TODO HLEDAT PODLE NAME NE ID
# PRIDAT ASSERT ERRORU Z KONZOLE

LOW PRIO:
TODO UKLADAT NAHODNY POCET SOUBORU
TODO UKLADAT NAHODNE SOUBORY
TODO DEFAULT NONE A NE PRAZDNY UVOZOVKY

'''